---
  version: "2"
  services: 
    shares: 
      image: "tianon/true"
      volumes: 
        - "/etc/localtime:/etc/localtime:ro"
    postgres: 
      image: "postgres:alpine"
      volumes_from: 
        - "shares"
      volumes: 
        - "./data/postgres:/var/lib/postgresql/data/pgdata"
      environment: 
        - "POSTGRES_USER=postgres"
        - "POSTGRES_PASSWORD=1234"
        - "PGDATA=/var/lib/postgresql/data/pgdata"
        - "POSTGRES_DB="
        - "POSTGRES_INITDB_ARGS="
    redis: 
      image: "redis:alpine"
      volumes_from: 
        - "shares"
      volumes: 
        - "./data/redis:/data"
      command: "redis-server --appendonly yes"
    kafka: 
      image: "spotify/kafka"
      ports: 
        - "2181:2181"
        - "9092:9092"
      environment: 
        - "ADVERTISED_HOST=127.0.0.1"
        - "ADVERTISED_PORT=9092"
        - "CONSUMER_THREADS=1"
        - "TOPICS="
        - "ZK_CONNECT=kafka7zookeeper:2181/root/path"
        - "GROUP_ID=mymirror"
